In [4]:
import numpy as np

print("Programa para calcular el promedio de las notas y saber si aprobaste")


notaAprobar = int(input("Ingrese la nota para aprobar el curso: "))
cantidad = int(input("Ingrese la cantidad de notas: "))


print(f"La cantidad de notas es: {cantidad}")

notas = []

for i in range(cantidad):
  nota = int(input(f"Ingrese la nota {i+1}: "))
  notas.append(nota)

# mean -> media
# median -> mediana
# mode -> moda

notas = np.array(notas)
promedio = round(notas.mean(), 2)
print(f"El promedio de las notas es {promedio}")

if promedio >= notaAprobar:
  print("Felicidades, aprobaste el curso")
else:
  print("Para el otro año será")

Programa para calcular el promedio de las notas y saber si aprobaste
Ingrese la nota para aprobar el curso: 14
Ingrese la cantidad de notas: 4
La cantidad de notas es: 4
Ingrese la nota 1: 15
Ingrese la nota 2: 8
Ingrese la nota 3: 18
Ingrese la nota 4: 20
El promedio de las notas es 15.25
Felicidades, aprobaste el curso


In [1]:
import numpy as np

print("Una matriz m x n")
filas = int(input("Ingrese el valor de m: "))
while filas <= 0:
  print("ERROR: m debe ser un valor positivo")
  filas = int(input("Ingrese el valor de m: "))
############################################
columnas = int(input("Ingrese el valor de n: "))
while columnas <= 0:
  print("ERROR: m debe ser un valor positivo")
  columnas = int(input("Ingrese el valor de n: "))

numeros = []

for i in range(filas):
  lista = []
  for j in range(columnas):
    numero = int(input(f"Ingresa el elemento en la posicion {i+1}x{j+1}: "))
    lista.append(numero)
  numeros.append(lista)

numeros = np.array(numeros)

print(numeros)

print("Suma de FILAS")
for i in range(filas):
  print(f"La suma de la fila {i+1} es: {numeros[i, :].sum()}")

print("Suma de COLUMNAS")
for j in range(columnas):
  print(f"La suma de la columna {j+1} es: {numeros[:, j].sum()}")


Una matriz m x n
Ingrese el valor de m: 3
Ingrese el valor de n: 3
Ingresa el elemento en la posicion 1x1: 1
Ingresa el elemento en la posicion 1x2: 2
Ingresa el elemento en la posicion 1x3: 3
Ingresa el elemento en la posicion 2x1: 4
Ingresa el elemento en la posicion 2x2: 5
Ingresa el elemento en la posicion 2x3: 6
Ingresa el elemento en la posicion 3x1: 7
Ingresa el elemento en la posicion 3x2: 8
Ingresa el elemento en la posicion 3x3: 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Suma de FILAS
La suma de la fila 1 es: 6
La suma de la fila 2 es: 15
La suma de la fila 3 es: 24
Suma de COLUMNAS
La suma de la columna 1 es: 12
La suma de la columna 2 es: 15
La suma de la columna 3 es: 18
